### ISSUE TITLE
README comment on storage (ACI vs AKS)

### ISSUE THREAD

**Issue by christophwille** [Inveniem/nextcloud-azure-aks#3]
"This approach offers significantly more flexibility for storage than trying to run Nextcloud on Azure Container Instances."

Could you please elaborate more on the differences why the ACI solution was dropped? Thanks. (reason: I wanted to bring up a simple trial environment to play with NextCloud, and ACI "seems" simpler than AKS for such a non-prod env)

**Comment by GuyPaddock** [comment]
@christophwille The issue was that ACI didn't give us any control over volume storage. We needed a way to do persistent volumes on Azure Files, and at the time we couldn't set the file mode/file permissions on the volumes mounted with ACI. Nextcloud is very particular about the owner and file mode of volumes; it will not launch or install if it detects that the data volume is not owned by the web user.

**Comment by christophwille** [comment]
Ah yes, I remember seeing an SO issue with the issue about permissions for the volume.

**Comment by GuyPaddock** [comment]
@christophwille At the time, ACI was also more expensive than just running AKS ourselves based on how the math worked out. You pay a premium so that you don't have the overhead of maintaining an AKS cluster, because you're shifting that overhead part of the TCO to Azure with margin added on their side.
